/pointcloud_to_laserscan:
  ros__parameters:
    angle_increment: 0.017453292519943295
    angle_max: 0.523
    angle_min: -0.523
    inf_epsilon: 1.0
    max_height: 1.0
    min_height: 0.2
    queue_size: 12
    range_max: 7.0
    range_min: 0.0
    scan_time: 0.1
    target_frame: base_link
    transform_tolerance: 0.01
    use_inf: true
    use_sim_time: false
