/pointcloud_to_laserscan:
  ros__parameters:
    angle_increment: 0.017453292519943295
    angle_max: 0.6109
    angle_min: -0.619
    max_height: 1.5
    min_height: 0.25
    queue_size: 20
    range_max: 7.0
    range_min: 0.0
    scan_time: 0.1
    target_frame: base_link
    transform_tolerance: 0.05
    use_inf: true
