/pointcloud_to_laserscan:
  ros__parameters:
    min_height: 0.25
    max_height: 1.5
    angle_min: -0.619
    angle_max: 0.6109
    angle_increment: 0.017453292519943295
    queue_size: 20
    scan_time: 0.1
    range_min: 0.0
    range_max: 7.0
    target_frame: base_link
    transform_tolerance: 0.05
    use_inf: true
